apiVersion: v1
kind: ConfigMap
metadata:
  name: home-assistant-config
  namespace: home-assistant
  labels:
    app: home-assistant
data:
  configuration.yaml: |
    default_config:

    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 10.42.0.0/16
  http-config.yaml: |
    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 10.42.0.0/16
